# Generated by Django 3.1.5 on 2021-01-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='level',
            field=models.CharField(choices=[('CR', 'Critical'), ('HI', 'High'), ('MD', 'Medium'), ('LO', 'Low'), ('IN', 'Informative')], default='MD', max_length=2),
        ),
    ]
